services:
  postgres:
    image: postgres:16-alpine
    container_name: opslens-postgres
    environment:
      POSTGRES_DB: opslens
      POSTGRES_USER: opslens
      POSTGRES_PASSWORD: opslens
    ports:
      - "5433:5432"
    volumes:
      - opslens-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U opslens -d opslens"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./spring-api
    container_name: opslens-backend
    ports:
      - "8081:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/opslens
      DB_USERNAME: opslens
      DB_PASSWORD: opslens
      API_KEY: ${API_KEY}
      AI_ORCHESTRATOR_URL: http://ai-orchestrator:8000
    depends_on:
      postgres:
        condition: service_healthy
      ai-orchestrator:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8081
    environment:
      API_INTERNAL_URL: http://backend:8080
    container_name: opslens-frontend
    ports:
      - "3001:3000"
    depends_on:
      backend:
        condition: service_healthy
  ai-orchestrator:
    build: ./ai-orchestrator
    container_name: opslens-ai-orchestrator
    ports:
      - "8002:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      # let you change the model without changing code
      # Usse OPENAI_MODEL if it exists
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o-mini}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_REPOSITORY_OWNER: ${GITHUB_REPOSITORY_OWNER}
      GITHUB_REPOSITORY_NAME: ${GITHUB_REPOSITORY_NAME}
      GITHUB_DEFAULT_BRANCH: ${GITHUB_DEFAULT_BRANCH:-main}
      CODE_SEARCH_MODE: ${CODE_SEARCH_MODE:-github}
      LOCAL_REPOSITORY_PATH: ${LOCAL_REPOSITORY_PATH:-/workspace/sketch-my-day}
    volumes:
      - ../sketch-my-day:/workspace/sketch-my-day:ro
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')",
        ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  opslens-postgres-data:
