spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      data-source-properties:
        prepareThreshold: 0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT:8080}

ai:
  orchestrator:
    url: ${AI_ORCHESTRATOR_URL:http://localhost:8002}
